export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const VALIDATE_SUCCESS = "VALIDATE_SUCCESS";
export const VALIDATE_FAIL = "VALIDATE_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SEND_EMAIL_PASSWORD_RECOVERY_SUCCESS = "SEND_EMAIL_PASSWORD_RECOVERY_SUCCESS";
export const SEND_EMAIL_PASSWORD_RECOVERY_FAIL = "SEND_EMAIL_PASSWORD_RECOVERY_FAIL";
export const PASSWORD_RECOVERY_SUCCESS = "PASSWORD_RECOVERY_SUCCESS";
export const PASSWORD_RECOVERY_FAIL = "PASSWORD_RECOVERY_FAIL";
export const LOGOUT = "LOGOUT";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_FAIL = "ADD_FAIL";
export const SUBS_TO_CART = "SUBS_TO_CART";
export const SUBS_FAIL = "SUBS_FAIL";
export const CHECKOUT = "CHECKOUT";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";
export const GET_CART = "GET_CART";
export const GET_CART_FAIL = "GET_CART_FAIL";
export const DELETE_CART = "DELETE_CART";
export const DESTROY_CART = "DESTROY_CART";
export const DESTROY_CART_FAIL = "DESTROY_CART_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";