var state = {
    "id": 1,
    "title": "Lucient",
    "created": "07/08/20",
    "description": "Lucient",
    "current_answers": [
        {"questions":"Quines són les teves influències?", "answers":"Les meves influències són moltes i molt variades. Vinc del rock i el Pop, abans de punxar electrònica vaig estar molts anys punxant «indie» i fins i tot vaig tocar en alguna banda, però també m’encanta la música negra, soul, funk, disco, afrobeat… També sóc un gran amant de la IDM i l’electrònica més experimental i quan no estic enfocat a una pista de ball els sons més balearics o fins i tot l’ambient o el jazz són dels discos que més escolto."},
        {"questions":"Quins elements són indispensables en la teva música?", "answers":"Em costa molt posar-li nom, ja que moltes vegades trio música que aparentment no té res a veure entre si, però que tenen aquell nosequè que em fa encendre una alarma dins el meu cap i em fa posar aquell disc a la maleta. Crec que un element bastant habitual en la música que punxo és que ajuden al viatge, ja sigui mental o físic."},
        {"questions":"Un disc que sempre portes en la teva maleta?", "answers":"Crec que un dels discs que més he punxat al llarg de la meva carrera és el Ne Noya (Daphni Mix) – Cos Ber Zam, que va publicar el mateix Daphni al seu segell, Jiaolong ara farà uns 10 anys."},
        {"questions":"Quins són els teus segells de referència?", "answers":"Segur que me’n deixo alguns, però sens dubte hi ha de ser Music From Memory, Whities (Que ara ha canviat el nom pel de AD 93), Antinote, Dark Entries, Early Sounds Recordings, Hivern, L.I.E.S., Livity Sound, Lobster Theremin o Craigie Knowes."},
        {"questions":"Com veus l’escena electrònica a Barcelona?", "answers":"Crec que l’escena electrònica de Barcelona viu un dels seus millors moments, bons artistes, varietat d’estils, un fotimer de botigues de discos especialitzades, clubs i festivals molt interessants (fora dels grans i habituals monstres de sempre, que també són importants). Fins i tot, crec que hi ha més col·laboracionisme que mai. El temps dirà i la perspectiva em donarà o no la raó, però si sabem treure suc de la situació de l’escena actual, en uns anys podem ser un referent més important dintre de l’escena electrònica global."}
    ], "introduction": "Mario G. Quelart porta ja uns quants anys mostrant el seu talent i «savoir faire» pels principals clubs i festivals del territori nacional. Ho fa sempre amb el nom de Lucient, o gairebé sempre, ja que de vegades s’ajunta amb Albert Salines (aka Wooky) amb el duet C.E.E. Shepherds. Lucient forma part de la família del segell Lapsus i del club LAUT de Barcelona, on és resident, i on s’ha posat a prova a si mateix amb dues maratonianes sessions de 12 hores non-stop, detall que indica per si sol el seu amplíssim coneixement de la música de ball de totes les èpoques i la seguretat amb la qual exerceix el seu ofici darrere dels plats. En Mario també dirigeix i presenta el programa «Synesthésiques«, a l’emissora local Dublab.es, i recentment ha estrenat el programa «Voyager» a C/C Radio. Entre les seves producción trobem remixes per artistas com la Museless i temes propis com el que trobem al recopilatori «Barca Is Not Barcelona», editat al segell d’Olde Gods, Minor Planets. Està treballant en el seu primer EP, que es preveu per algun moment del 2021.",
    "image": "https://ameba.cat/wp-content/uploads/2020/08/IMG_5459-scaled.jpg"
}

export default state;